// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_content_delivery_bucket": "mobilectrl-20181222110315--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://mobilectrl-20181222110315--hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:413c5850-5af2-41d8-971c-b51a88c4ae64",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_QwJMvsFQ2",
    "aws_user_pools_web_client_id": "731gb14utpeh19c1h7kecuqage"
};


export default awsmobile;
