// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:1821ba27-3b15-46f5-8685-08f7af07e71f",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NftTpgKc7",
    "aws_user_pools_web_client_id": "7jf1tqk593p161lbetkfgq9jse",
    "aws_content_delivery_bucket": "mobilectrl-20181206130007--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://mobilectrl-20181206130007--hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cloud_logic_custom": [
        {
            "name": "iotShadowAPIGet",
            "endpoint": "https://yyzizl2p26.execute-api.us-west-2.amazonaws.com/Prod",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
