service: iot-shadow-rest
provider:
  name: aws
  stage: Prod
  runtime: python2.7
  region: us-west-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "iot:*"
      Resource:
        - "*"
functions:
  shadow_get:
    handler: main.get
    events:
      - http:
          path: /shadow/{id}
          method: GET
          resp: http
          request:
            parameters:
              paths:
                id: true
          cors: true
  shadow_post:
    handler: main.post
    events:
      - http:
          path: /shadow/update/{id}
          method: POST
          resp: http
          request:
            parameters:
              paths:
                id: true
          cors: true
custom:
  pythonRequirements:
    dockerizePip: True
plugins:
  - serverless-python-requirements

